export const data = [
  {
    id: 1,
    class: "Electric Guitar",
    image: "https://images2.imgbox.com/5b/c2/mRfJsvlT_o.png",
    brand: "Ibanez",
    model: "RG-JEMJR",
    pickups: "Quantum Neck/Bridge HB",
    bridge: "Double Locking Tremolo",
    signature: "Steve Vai",
    strings: "6",
    body: "Mahogany",
    price: 187.242,
    stock: 8,
  },
  {
    id: 2,
    class: "Electric Guitar",
    image: "https://images2.imgbox.com/24/d0/1y9yvpYh_o.png",
    brand: "ESP",
    model: "Deluxe EC-1000",
    pickups: "Seymour Duncan JB",
    bridge: "TonePros Tune-O-Matic",
    signature: "No",
    strings: "6",
    body: "Mahogany",
    price: 344.199,
    stock: 5,
  },
  {
    id: 3,
    class: "Electric Guitar",
    image: "https://images2.imgbox.com/79/9a/okw93F7e_o.png",
    brand: "PRS",
    model: "30 Anniversary S2",
    pickups: "HFS/Vintage PRS SE",
    bridge: "PRS Tremolo",
    signature: "No",
    strings: "6",
    body: "Alder",
    price: 212.162,
    stock: 7,
  },
  {
    id: 4,
    class: "Electric Guitar",
    image: "https://images2.imgbox.com/ab/9f/UzcpPya2_o.png",
    brand: "Fender",
    model: "Vintage American 52",
    pickups: "Tele Single-Coil",
    bridge: "Tele AV 3-Silla",
    signature: "No",
    strings: "6",
    body: "Swamp Ash",
    price: 681.308,
    stock: 4,
  },
  {
    id: 5,
    class: "Electric Guitar",
    image: "https://images2.imgbox.com/5e/df/0UMc1gIi_o.png",
    brand: "Gibson",
    model: "Cardinal Red 19",
    pickups: "Mini Firebird Humbucker",
    bridge: "Nashville ALM Tune-O-Matic",
    signature: "No",
    strings: "6",
    body: "Mahogany",
    price: 327.531,
    stock: 9,
  },
  {
    id: 6,
    class: "Electric Guitar",
    image: "https://images2.imgbox.com/08/8f/dCc6ZQcn_o.png",
    brand: "Schecter",
    model: "C-6 FR Pro",
    pickups: "Schecter Diamond Decimator",
    bridge: "SPC Hot Rod Floyd Rose",
    signature: "No",
    strings: "6",
    body: "Mahogany",
    price: 298.724,
    stock: 6,
  },
  {
    id: 7,
    class: "Electric Bass",
    image: "https://images2.imgbox.com/d6/dc/f3GS8GlO_o.png",
    brand: "Fender",
    model: "Steve Harris Precision Bass",
    pickups: "Seymour Duncan SPB-1",
    bridge: "Leo Quan Badass II",
    signature: "Steve Harris",
    strings: "4",
    body: "Alder",
    price: 378.516,
    stock: 4,
  },
  {
    id: 8,
    class: "Electric Bass",
    image: "https://images2.imgbox.com/19/5f/B8Ia452M_o.png",
    brand: "Jackson",
    model: "JS JS3 Series",
    pickups: "Jackson Humbucking",
    bridge: "Jackson HiMass™",
    signature: "No",
    strings: "4",
    body: "Basswood",
    price: 120.963,
    stock: 7,
  },
  {
    id: 9,
    class: "Electric Bass",
    image: "https://images2.imgbox.com/e9/5b/XZdTIO02_o.png",
    brand: "Gibson",
    model: "EB Bass",
    pickups: "EB Bass Gibson Humbucker",
    bridge: "Full Contact Babicz",
    signature: "No",
    strings: "5",
    body: "Ash",
    price: 228.646,
    stock: 5,
  },
  {
    id: 10,
    class: "Electric Bass",
    image: "https://images2.imgbox.com/b5/14/MZ0jShIl_o.png",
    brand: "Dean",
    model: "5-S Bass Edge Select",
    pickups: "DMT Passive Soapbar Series",
    bridge: "High-Mass Bass Bridge",
    signature: "No",
    strings: "5",
    body: "Swamp Ash",
    price: 184.923,
    stock: 8,
  },
  {
    id: 11,
    class: "Electric Bass",
    image: "https://images2.imgbox.com/5b/8c/VNls7KeD_o.png",
    brand: "Warwick",
    model: "Corvette B Rockbass",
    pickups: "Active MEC J/J",
    bridge: "Just-A-Nut III",
    signature: "No",
    strings: "4",
    body: "Alder",
    price: 156.382,
    stock: 6,
  },
  {
    id: 12,
    class: "Electric Bass",
    image: "https://images2.imgbox.com/2c/d9/ZOxPINkg_o.png",
    brand: "ESP",
    model: "Surveyor 87 Bass",
    pickups: "Vintage Seymour Duncan Jazz/P",
    bridge: "Gotoh 201B-4",
    signature: "No",
    strings: "4",
    body: "Alder",
    price: 236.472,
    stock: 9,
  },
];
